import {
  Banner,
  Banner_Block,
  OurClients,
  OurClients_Block,
  Statistics,
  Statistics_Block,
  TeamInfo,
  TeamInfo_Block,
  VideoArea,
  VideoArea_Block,
} from './About'
import { AuthorHero, Author_Hero_Block } from './Author'
import { BlogHero, Blog_Hero_Block } from './Blog'
import {
  About,
  About_Block,
  Advertise,
  Advertise_Block,
  Headline,
  Headline_Block,
  Hero,
  Hero_Block,
  RecentWork,
  RecentWork_Block,
  Service,
  Service_Block,
  Skills,
  Skills_Block,
  Team,
  Team_Block,
  Testimonial,
  Testimonial_Block,
} from './Home'
import {
  Contact,
  Contact_Block,
  PageBanner,
  PageBanner_Block,
  PricingFeatures,
  PricingFeatures_Block,
  PricingSection,
  PricingSection_Block,
} from './Pricing'
import {
  ServiceBanner,
  ServiceBanner_Block,
  ServiceFeatures,
  ServiceFeatures_Block,
  WorkProcess,
  WorkProcess_Block,
} from './Services'
import { TagsHero, Tags_Hero_Block } from './Tag'

export const blocksJSX = {
  Advertise,
  Headline,
  About,
  Hero,
  RecentWork,
  Service,
  Skills,
  Team,
  Testimonial,
  Banner,
  OurClients,
  Statistics,
  TeamInfo,
  VideoArea,
  ServiceBanner,
  ServiceFeatures,
  WorkProcess,
  TagsHero,
  AuthorHero,
  PageBanner,
  PricingFeatures,
  PricingSection,
  Contact,
  BlogHero,
}

export type SlugType = keyof typeof blocksJSX

export const blocks = [
  Advertise_Block,
  Headline_Block,
  About_Block,
  Hero_Block,
  RecentWork_Block,
  Service_Block,
  Skills_Block,
  Team_Block,
  Testimonial_Block,
  Banner_Block,
  OurClients_Block,
  Statistics_Block,
  TeamInfo_Block,
  VideoArea_Block,
  ServiceBanner_Block,
  ServiceFeatures_Block,
  WorkProcess_Block,
  Tags_Hero_Block,
  Author_Hero_Block,
  PageBanner_Block,
  PricingFeatures_Block,
  PricingSection_Block,
  Contact_Block,
  Blog_Hero_Block,
]
